<?php

require "conn.php";
//create booking
//after patient confirms booking, send the booking information to the database

$patient ='kananelomokoko1@gmail.com';// $_POST["email"]; //use email to uniquely identify patient user who created the new booking
// DATE MUST BE YYYY-MM-DD HH:MM:SS

$booking_date ='2021-06-17';// $_POST["date"]; //this is the time and date that the user has made the appointment to be
$booking_time ='09:00 am';// $_POST["time"];
$dr_email ='kananelomokoko@gmail.com';// $_POST["doc_email"];
$token='e4F5NOGYSSuU3F1fC-CZ3d:APA91bGtMASr_NpnvY5xXJU4U4-C_lb4Q2h1xcVu67fh8nnfcV1n2fJ-7nQ17TX_FfbX0PhC4nMKhO9s5A6jM1QKPhgb35QRhQR7tTNHWJyWZI9nMcUXd-UbYyue4zvDk2BuW6L3_oOj';//;$_POST["token"]; //this is the token taken from the query in doctors_list.php *
$reason = 'I am sick'; //$_POST["reason"]; //why visit

$doctor_spec ='General';// $_POST["specialisation"];
//should I add doctor experience?

function notify($to,$data){

    $api_key="AAAAZO7u-t4:APA91bEkehnr2HGLpeEP54kIoz56VD3SghqiaelR3DnFE2Wfn_lLboHrVbVlekEvnNm5sk1S6UXj-_1u8CDGnWbJofhSkFSmLjLg0PZi3-34Q5XDf0Hn7zBsuMJZbZXM8YqoZ0E2ncbC";
    $url="https://fcm.googleapis.com/fcm/send";
    $fields=json_encode(array('to'=>$to,'notification'=>$data));
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));

    $headers = array();
    $headers[] = 'Authorization: key ='.$api_key;
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
}



if(!empty($patient) && !empty($booking_date)  && !empty($doctor_spec) && !empty($dr_email) && !empty($token)){
    $pending = mysqli_query($conn,"SELECT PATIENT_EMAIL FROM BOOKINGS WHERE PATIENT_EMAIL='$patient' AND STATUS='PENDING'");
    $accepted= mysqli_query($conn,"SELECT PATIENT_EMAIL FROM BOOKINGS WHERE PATIENT_EMAIL='$patient' AND STATUS='ACCEPTED'");
    if (mysqli_num_rows($pending)==1 || mysqli_num_rows($accepted)==1 ) {
	    echo "Cannot create booking. You already have a booking in progress.";
	}
    elseif(mysqli_num_rows($pending)==0 && mysqli_num_rows($accepted)==0){

        if (empty($reason)) {
            $insert = "INSERT INTO BOOKINGS(PATIENT_EMAIL, DOCTOR_EMAIL, BOOKING_DATE,BOOKING_TIME ) VALUES('$patient', '$dr_email', '$booking_date', '$booking_time')";
        }
        else{
            $insert = "INSERT INTO BOOKINGS(PATIENT_EMAIL, DOCTOR_EMAIL, BOOKING_DATE,BOOKING_TIME, REASON) VALUES('$patient', '$dr_email', '$booking_date', '$booking_time', '$reason')";
        }
    
        $sql = mysqli_query($conn, $insert);
        if ($sql) {
            echo "Booking was created successfully!";
                //notify the doctor about the newly created booking

            $data=array(
                'title'=>'NEW NOTIFICATION',
                'body'=>'PATIENT HAS CREATED A BOOKING'
            );

            $to = $token;
            notify($to,$data);

            //notify the patient about the booking invite that has been accepted in a different file
        }
        else{
            echo "Failed to create booking!";
        }

    }
	else{ echo "There are illegal bookings";}
    
}

else{
    echo "There may be empty inputs";
}
mysqli_close($conn); 
?>
