<?php

require "conn.php";
//create booking
//after patient confirms booking, send the booking information to the database

$patient =$_POST["email"]; //use email to uniquely identify patient user who created the new booking
// DATE MUST BE YYYY-MM-DD HH:MM:SS

$booking_date =$_POST["date"]; //this is the time and date that the user has made the appointment to be
$booking_time =$_POST["time"];
$dr_email =$_POST["doc_email"];
$token = $_POST["token"]; //this is the token taken from the query in doctors_list.php *
$reason = $_POST["reason"]; //why visit

$doctor_spec =$_POST["specialisation"];
//should I add doctor experience?

function notify($to,$data){

    $api_key="AIzaSyBVEqD8Ar4QgNETZEDPG2r3NZ-ykttyDWM";
    $url="https://fcm.googleapis.com/fcm/send";
    $fields=json_encode(array('to'=>$to,'notification'=>$data));
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));

    $headers = array();
    $headers[] = 'Authorization: key ='.$api_key;
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
}



if(!empty($patient) && !empty($booking_date)  && !empty($doctor_spec) && !empty($dr_email) && !empty($token)){
    $pending = mysqli_query($conn,"SELECT PATIENT_EMAIL FROM BOOKINGS WHERE PATIENT_EMAIL='$patient' AND STATUS='PENDING'");
    $accepted= mysqli_query($conn,"SELECT PATIENT_EMAIL FROM BOOKINGS WHERE PATIENT_EMAIL='$patient' AND STATUS='ACCEPTED'");
    if (mysqli_num_rows($pending)==1 || mysqli_num_rows($accepted)==1 ) {
	    echo "Cannotcreatebooking.Youalreadyhaveabookinginprogress.  ";
	}
    elseif(mysqli_num_rows($pending)==0 && mysqli_num_rows($accepted)==0){
// postTotheLamp(emailAddress);
        if (empty($reason)) {
            $insert = "INSERT INTO BOOKINGS(PATIENT_EMAIL, DOCTOR_EMAIL, BOOKING_DATE,BOOKING_TIME ) VALUES('$patient', '$dr_email', '$booking_date', '$booking_time')";
        }
        else{
            $insert = "INSERT INTO BOOKINGS(PATIENT_EMAIL, DOCTOR_EMAIL, BOOKING_DATE,BOOKING_TIME, REASON) VALUES('$patient', '$dr_email', '$booking_date', '$booking_time', '$reason')";
        }
    
        $sql = mysqli_query($conn, $insert);
        if ($sql) {
            
                //notify the doctor about the newly created booking
	      $to = $token;
            $data=array(
                'title'=>'NEW NOTIFICATION',
                'body'=>'PATIENT HAS CREATED A BOOKING'
            );
           
            notify($to,$data);
	    echo "Bookingwascreatedsuccessfully!  ";

            //notify the patient about the booking invite that has been accepted in a different file
        }
        else{
            echo "Failedtocreatebooking!  ";
        }

    }
	else{ echo "Thereareillegalbookings ";}
    
}

else{
    echo "Theremaybeemptyinputs   ";
}
mysqli_close($conn); 
?>
